name: Build & Deploy MakeCode (micro:bit)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install pxt CLI
        run: npm install -g pxt

      - name: Install target dependencies
        run: npm ci

      # Build static site to ./built
      - name: Build static package
        run: pxt staticpkg

      # Publish ./built to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./built
          publish_branch: gh-pages
          force_orphan: true

      - name: Print Pages URL
        run: |
          echo "Your site will be: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/#editor"
